export enum UserRole { ADMIN = 'ADMIN', RESIDENT_OWNER = 'RESIDENT_OWNER', RESIDENT_TENANT = 'RESIDENT_TENANT', GUARD = 'GUARD', VENDOR = 'VENDOR', SUPPLIER = 'SUPPLIER' }
export enum SupplierCategory {
  WATER_SUPPLY = 'WATER_SUPPLY',
  DIESEL_FUEL = 'DIESEL_FUEL',
  CHEMICALS_TREATMENT = 'CHEMICALS_TREATMENT',
  ELECTRICAL_HARDWARE = 'ELECTRICAL_HARDWARE',
  PLUMBING_HARDWARE = 'PLUMBING_HARDWARE',
  HOUSEKEEPING_BULK = 'HOUSEKEEPING_BULK',
  LANDSCAPING = 'LANDSCAPING',
  BAZAAR_WHOLESALE = 'BAZAAR_WHOLESALE',
}
export enum PurchaseOrderStatus {
  NEW_PO = 'NEW_PO',
  CONFIRMED = 'CONFIRMED',
  DISPATCHED = 'DISPATCHED',
  DELIVERED = 'DELIVERED',
  INVOICED = 'INVOICED',
  CANCELLED = 'CANCELLED',
}
export enum DeliveryChallanStatus {
  DISPATCHED = 'DISPATCHED',
  AT_GATE = 'AT_GATE',
  INSPECTED = 'INSPECTED',
  OFFLOADED = 'OFFLOADED',
  GATE_EXIT = 'GATE_EXIT',
}
export enum SupplierInvoiceStatus {
  DRAFT = 'DRAFT',
  ISSUED = 'ISSUED',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
}
export enum VisitCategory { MEDICAL = 'MEDICAL', TECHNICAL = 'TECHNICAL', DOMESTIC_HELPER = 'DOMESTIC_HELPER', TRANSIT = 'TRANSIT', DELIVERY = 'DELIVERY', GUEST = 'GUEST' }
export enum VisitPurpose { DELIVERY = 'DELIVERY', GUEST = 'GUEST', MAINTENANCE = 'MAINTENANCE', CAB = 'CAB' }
export enum TicketStatus { OPEN = 'OPEN', ASSIGNED = 'ASSIGNED', IN_PROGRESS = 'IN_PROGRESS', PENDING_VERIFICATION = 'PENDING_VERIFICATION', CLOSED = 'CLOSED' }
export enum TicketCategory { PLUMBING = 'PLUMBING', ELECTRICAL = 'ELECTRICAL', ROAD_SWEEPING = 'ROAD_SWEEPING', GARBAGE = 'GARBAGE', OTHER = 'OTHER' }
export enum TicketPriority { LOW = 'LOW', MEDIUM = 'MEDIUM', HIGH = 'HIGH', URGENT = 'URGENT' }
export enum BillingCycle { MONTHLY = 'MONTHLY', QUARTERLY = 'QUARTERLY', YEARLY = 'YEARLY' }
export enum TenancyType { OWNER = 'OWNER', TENANT = 'TENANT' }
export enum PaymentStatus { PENDING = 'PENDING', PAID = 'PAID', OVERDUE = 'OVERDUE', WAIVED = 'WAIVED' }
export enum InvoiceStatus { DRAFT = 'DRAFT', ISSUED = 'ISSUED', PAID = 'PAID', OVERDUE = 'OVERDUE', CANCELLED = 'CANCELLED' }
export enum LedgerEntryType { DEBIT = 'DEBIT', CREDIT = 'CREDIT' }
export enum EventPoolStatus { DRAFT = 'DRAFT', OPEN = 'OPEN', VOTING = 'VOTING', LOCKED = 'LOCKED', ACTIVE = 'ACTIVE', RECONCILED = 'RECONCILED', CLOSED = 'CLOSED' }
export enum PoolParticipantRole { PARTNER = 'PARTNER', SPONSOR = 'SPONSOR' }
export enum SurplusResolution { ROLLOVER = 'ROLLOVER', CASHBACK = 'CASHBACK', COMMUNITY_POLL = 'COMMUNITY_POLL' }
export enum OrderStatus { PENDING = 'PENDING', CONFIRMED = 'CONFIRMED', PREPARING = 'PREPARING', OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY', DELIVERED = 'DELIVERED', CANCELLED = 'CANCELLED' }
export enum ChatChannelType { ANNOUNCEMENT = 'ANNOUNCEMENT', GENERAL = 'GENERAL', COMMITTEE = 'COMMITTEE', SECURITY_ALERT = 'SECURITY_ALERT' }
export enum FacilityPricingTier { RESIDENT = 'RESIDENT', EXTERNAL = 'EXTERNAL' }

