import { Share, Platform, Linking, Alert } from 'react-native';
import { SocietyEvent } from '../stores/eventStore';

/**
 * Parses event date string (e.g. "Sat, 10 Oct 2026") into YYYYMMDD format.
 */
export function formatCalendarDate(dateStr: string): string {
  try {
    const cleaned = dateStr.replace(/^[A-Za-z]+,\s*/, '').trim();
    const d = new Date(cleaned);
    if (!isNaN(d.getTime())) {
      const year = d.getFullYear();
      const month = String(d.getMonth() + 1).padStart(2, '0');
      const day = String(d.getDate()).padStart(2, '0');
      return `${year}${month}${day}`;
    }
  } catch (e) {}

  // Fallback to today + 7 days
  const fallback = new Date(Date.now() + 86400000 * 7);
  return `${fallback.getFullYear()}${String(fallback.getMonth() + 1).padStart(2, '0')}${String(fallback.getDate()).padStart(2, '0')}`;
}

/**
 * Generates a one-tap Google Calendar web template URL that allows residents
 * to instantly block time on their personal Google Calendar on Android, iOS, or Web.
 */
export function generateGoogleCalendarUrl(event: SocietyEvent): string {
  const dateBase = formatCalendarDate(event.date);
  // Default 08:00 AM to 06:00 PM in UTC format
  const startStamp = `${dateBase}T080000Z`;
  const endStamp = `${dateBase}T180000Z`;

  const detailsText =
    `AMA Community Event: ${event.title}\n\n` +
    `📍 Location: ${event.location}\n` +
    `👤 Organized by: ${event.organizerName} (${event.organizerFlat})\n\n` +
    `🗺️ PLACES TO VISIT & SCHEDULE:\n` +
    (event.placesToVisit && event.placesToVisit.length > 0
      ? event.placesToVisit
          .map(
            (p, idx) =>
              `${idx + 1}. ${p.placeName} (${p.startTime} - ${p.endTime})\n   Time to spend: ${p.timeToSpend}\n   Actions: ${p.actions}`
          )
          .join('\n\n')
      : event.description) +
    `\n\nGenerated by AMA Apartment Management App.`;

  return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(
    event.title
  )}&dates=${startStamp}/${endStamp}&details=${encodeURIComponent(detailsText)}&location=${encodeURIComponent(
    event.location
  )}`;
}

/**
 * Generates and downloads an iCalendar (.ics) file so residents can import
 * the event directly into Apple Calendar, Outlook, or Google Calendar offline.
 */
export function downloadEventIcsFile(event: SocietyEvent): void {
  const dateBase = formatCalendarDate(event.date);
  const startStamp = `${dateBase}T080000Z`;
  const endStamp = `${dateBase}T180000Z`;

  let scheduleLines = '';
  if (event.placesToVisit && event.placesToVisit.length > 0) {
    scheduleLines = event.placesToVisit
      .map((p, idx) => `${idx + 1}. ${p.placeName} (${p.startTime} - ${p.endTime}, Time: ${p.timeToSpend}): ${p.actions}`)
      .join('\\n');
  }

  const icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//AMA Apartment Management//Community Events//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'BEGIN:VEVENT',
    `UID:ama-event-${event.id}@apartmentmanagement.app`,
    `DTSTAMP:${startStamp}`,
    `DTSTART:${startStamp}`,
    `DTEND:${endStamp}`,
    `SUMMARY:${event.title.replace(/[\n\r]/g, '')}`,
    `DESCRIPTION:${event.description.replace(/[\n\r]/g, ' ')}\\n\\nSchedule:\\n${scheduleLines}`,
    `LOCATION:${event.location.replace(/[\n\r]/g, ' ')}`,
    'STATUS:CONFIRMED',
    'END:VEVENT',
    'END:VCALENDAR',
  ].join('\r\n');

  if (Platform.OS === 'web' && typeof window !== 'undefined' && typeof document !== 'undefined') {
    try {
      const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
      const link = document.createElement('a');
      link.href = window.URL.createObjectURL(blob);
      link.setAttribute('download', `AMA-Event-${event.id}.ics`);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      Alert.alert('Calendar File Downloaded', `Saved AMA-Event-${event.id}.ics to your downloads.`);
      return;
    } catch (err) {
      console.warn('ICS download error on web', err);
    }
  }

  // Mobile fallback: open Google Calendar URL
  const calUrl = generateGoogleCalendarUrl(event);
  Linking.openURL(calUrl).catch(() => {
    Alert.alert('Calendar Link', 'Unable to open calendar application directly.');
  });
}

/**
 * String padding helper for tabular alignment in WhatsApp monospace blocks
 */
function pad(text: string, width: number, align: 'left' | 'right' = 'left'): string {
  const str = String(text ?? '');
  if (str.length > width) {
    return str.substring(0, width - 1) + '…';
  }
  return align === 'right' ? str.padStart(width, ' ') : str.padEnd(width, ' ');
}

function createDivider(colWidths: number[], type: 'top' | 'mid' | 'bot'): string {
  const left = type === 'top' ? '┌' : type === 'mid' ? '├' : '└';
  const mid = type === 'top' ? '┬' : type === 'mid' ? '┼' : '┴';
  const right = type === 'top' ? '┐' : type === 'mid' ? '┤' : '┘';
  return left + colWidths.map((w) => '─'.repeat(w + 2)).join(mid) + right;
}

function createRow(cells: string[], colWidths: number[], aligns: Array<'left' | 'right'> = []): string {
  return (
    '│ ' +
    cells
      .map((cell, idx) => pad(cell, colWidths[idx], aligns[idx] || 'left'))
      .join(' │ ') +
    ' │'
  );
}

function wrapText(text: string, maxWidth: number): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let currentLine = '';
  words.forEach((word) => {
    if ((currentLine + (currentLine ? ' ' : '') + word).length <= maxWidth) {
      currentLine += (currentLine ? ' ' : '') + word;
    } else {
      if (currentLine) lines.push(currentLine);
      currentLine = word;
    }
  });
  if (currentLine) lines.push(currentLine);
  return lines;
}

function createFullWidthRows(content: string, colWidths: number[], prefix = '  ► '): string[] {
  const rowLen = createDivider(colWidths, 'top').length;
  const innerWidth = rowLen - 4;
  const availableWidth = innerWidth - prefix.length;
  const lines = wrapText(content, availableWidth);
  return lines.map((line, idx) => {
    const pfx = idx === 0 ? prefix : ' '.repeat(prefix.length);
    return '│ ' + pad(pfx + line, innerWidth, 'left') + ' │';
  });
}

/**
 * Formats a comprehensive WhatsApp message in a neat, professional tabular format containing:
 * - Event Overview Table
 * - Places to Visit & Schedule Table (with time window, spend, destination, actions, and ticket cost)
 * - Financial Budget & Pool Table
 * - Purchaser Payments & Reimbursement Settlement Table (who purchased, amount paid, fair share, net reimbursement balance)
 * - Itemized Expense Log Table
 * - Resident Pool Contributions Table
 * - Direct one-tap Calendar Block Link
 */
export function formatEventWhatsAppPlan(event: SocietyEvent): string {
  const gcalUrl = generateGoogleCalendarUrl(event);

  // Compute expense calculations
  const expenses = event.expenses || [];
  const contributions = event.contributions || [];
  const places = event.placesToVisit || [];

  const totalSpent = expenses.reduce((sum, exp) => sum + exp.amount, 0);
  const totalCollected = event.budget.collected || contributions.reduce((sum, c) => sum + c.amount, 0);
  const attendeeCount = Math.max(1, event.attendeesCount || 1);
  const perPersonShare = Math.round((totalSpent > 0 ? totalSpent : event.budget.total) / attendeeCount);

  // Group expenses by purchaser
  const purchaserSummary: Record<string, { totalPaid: number; flat: string; items: string[] }> = {};
  expenses.forEach((exp) => {
    const key = exp.paidBy;
    if (!purchaserSummary[key]) {
      purchaserSummary[key] = { totalPaid: 0, flat: exp.paidByFlat, items: [] };
    }
    purchaserSummary[key].totalPaid += exp.amount;
    purchaserSummary[key].items.push(`${exp.title} (₹${exp.amount.toLocaleString()})`);
  });

  // 1. Event Overview Table
  const overviewColWidths = [14, 38];
  const overviewTable = [
    '```',
    createDivider(overviewColWidths, 'top'),
    '│ ' + pad('🎪 AMA SOCIETY EVENT OVERVIEW', createDivider(overviewColWidths, 'top').length - 4, 'left') + ' │',
    '├' + '─'.repeat(createDivider(overviewColWidths, 'top').length - 2) + '┤',
    createRow(['Event', event.title], overviewColWidths),
    createRow(['Date & Timing', `${event.date} • ${event.time}`], overviewColWidths),
    createRow(['Assembly/Venue', event.location], overviewColWidths),
    createRow(['Confirmed RSVP', `${event.attendeesCount} Residents Attending`], overviewColWidths),
    createRow(['Organized By', `${event.organizerName} (${event.organizerFlat})`], overviewColWidths),
    createDivider(overviewColWidths, 'bot'),
    '```',
  ].join('\n');

  // 2. Places to Visit & Schedule Table
  let scheduleSection = '';
  if (places.length > 0) {
    const placeColWidths = [2, 20, 8, 20, 9];
    const placeRows: string[] = [
      '🗺️ *PLACES TO VISIT & SCHEDULE (ITINERARY)*',
      '```',
      createDivider(placeColWidths, 'top'),
      createRow(['#', 'Time Window', 'Spend', 'Destination', 'Entry Fee'], placeColWidths),
      createDivider(placeColWidths, 'mid'),
    ];

    places.forEach((p, idx) => {
      const feeStr = p.ticketCostPerPerson && p.ticketCostPerPerson > 0 ? `₹${p.ticketCostPerPerson}/pax` : 'Free';
      const timeStr = `${p.startTime}-${p.endTime}`;
      placeRows.push(createRow([String(idx + 1), timeStr, p.timeToSpend, p.placeName, feeStr], placeColWidths));
      if (p.actions) {
        createFullWidthRows(`Actions: ${p.actions}`, placeColWidths, '  ► ').forEach((r) => placeRows.push(r));
      }
      if (p.address) {
        createFullWidthRows(`Landmark: ${p.address}`, placeColWidths, '  📍 ').forEach((r) => placeRows.push(r));
      }
      if (idx < places.length - 1) {
        placeRows.push(createDivider(placeColWidths, 'mid'));
      }
    });

    placeRows.push(createDivider(placeColWidths, 'bot'));
    placeRows.push('```\n');
    scheduleSection = placeRows.join('\n');
  }

  // 3. Financial Budget Pool Table
  const budgetColWidths = [24, 26];
  const budgetRows: string[] = [
    '💰 *EXPENSE TRACKER & FINANCIAL POOL SUMMARY*',
    '```',
    createDivider(budgetColWidths, 'top'),
    createRow(['Financial Pool Metric', 'Amount (INR)'], budgetColWidths),
    createDivider(budgetColWidths, 'mid'),
    createRow(['Total Budget Target', `₹ ${event.budget.total.toLocaleString()}`], budgetColWidths, ['left', 'right']),
    createRow(['Total Incurred / Spent', `₹ ${totalSpent.toLocaleString()}`], budgetColWidths, ['left', 'right']),
    createRow(['Total Pool Collected', `₹ ${totalCollected.toLocaleString()}`], budgetColWidths, ['left', 'right']),
    createRow(['Fair Share Per Person', `₹ ${perPersonShare.toLocaleString()} (${attendeeCount} pax)`], budgetColWidths, ['left', 'right']),
  ];
  const netPool = totalCollected - totalSpent;
  if (netPool >= 0) {
    budgetRows.push(createRow(['Pool Surplus Balance', `+₹ ${netPool.toLocaleString()}`], budgetColWidths, ['left', 'right']));
  } else {
    budgetRows.push(createRow(['Pool Deficit (Pending)', `-₹ ${Math.abs(netPool).toLocaleString()}`], budgetColWidths, ['left', 'right']));
  }
  budgetRows.push(createDivider(budgetColWidths, 'bot'));
  budgetRows.push('```\n');
  const budgetSection = budgetRows.join('\n');

  // 4. Purchaser Contributions & Reimbursement Settlement Table
  let purchaserSection = '';
  const purchaserEntries = Object.entries(purchaserSummary);
  if (purchaserEntries.length > 0) {
    const purchaserColWidths = [2, 23, 9, 8, 18];
    const purchaserRows: string[] = [
      '💳 *PURCHASER PAYMENT CONTRIBUTIONS & REIMBURSEMENT BALANCES*',
      '```',
      createDivider(purchaserColWidths, 'top'),
      createRow(['#', 'Purchaser (Unit)', 'Paid', 'Share', 'Net Settlement'], purchaserColWidths),
      createDivider(purchaserColWidths, 'mid'),
    ];

    purchaserEntries.forEach(([name, data], idx) => {
      const netReimbursement = data.totalPaid - perPersonShare;
      const settlementStr = netReimbursement > 0 ? `+₹${netReimbursement.toLocaleString()} to Recv` : 'Settled';
      purchaserRows.push(createRow(
        [String(idx + 1), `${name} (${data.flat})`, `₹ ${data.totalPaid.toLocaleString()}`, `₹ ${perPersonShare.toLocaleString()}`, settlementStr],
        purchaserColWidths,
        ['left', 'left', 'right', 'right', 'left']
      ));
      if (data.items.length > 0) {
        createFullWidthRows(`Items: ${data.items.join(', ')}`, purchaserColWidths, '  ► ').forEach((r) => purchaserRows.push(r));
      }
      if (idx < purchaserEntries.length - 1) {
        purchaserRows.push(createDivider(purchaserColWidths, 'mid'));
      }
    });

    purchaserRows.push(createDivider(purchaserColWidths, 'bot'));
    purchaserRows.push('```\n');
    purchaserSection = purchaserRows.join('\n');
  }

  // 5. Itemized Purchases Log Table
  let itemizedSection = '';
  if (expenses.length > 0) {
    const expenseColWidths = [2, 25, 11, 23, 9];
    const expenseRows: string[] = [
      '🧾 *ITEMIZED EXPENSE LOG (WHO PURCHASED WHAT)*',
      '```',
      createDivider(expenseColWidths, 'top'),
      createRow(['#', 'Purchase Item', 'Category', 'Paid By (Flat)', 'Amount'], expenseColWidths),
      createDivider(expenseColWidths, 'mid'),
    ];

    expenses.forEach((exp, idx) => {
      expenseRows.push(createRow(
        [String(idx + 1), exp.title, exp.category, `${exp.paidBy} (${exp.paidByFlat})`, `₹ ${exp.amount.toLocaleString()}`],
        expenseColWidths,
        ['left', 'left', 'left', 'left', 'right']
      ));
      if (exp.notes) {
        createFullWidthRows(`Note: ${exp.notes}`, expenseColWidths, '  📝 ').forEach((r) => expenseRows.push(r));
      }
      if (idx < expenses.length - 1) {
        expenseRows.push(createDivider(expenseColWidths, 'mid'));
      }
    });

    expenseRows.push(createDivider(expenseColWidths, 'bot'));
    expenseRows.push('```\n');
    itemizedSection = expenseRows.join('\n');
  }

  // 6. Resident Pool Contributions Table (if any)
  let contribSection = '';
  if (contributions.length > 0) {
    const contribColWidths = [2, 18, 9, 12, 11];
    const contribRows: string[] = [
      '📥 *RESIDENT POOL CONTRIBUTIONS*',
      '```',
      createDivider(contribColWidths, 'top'),
      createRow(['#', 'Contributor', 'Amount', 'Method', 'Date'], contribColWidths),
      createDivider(contribColWidths, 'mid'),
    ];

    contributions.forEach((c, idx) => {
      contribRows.push(createRow(
        [String(idx + 1), `${c.contributorName} (${c.contributorFlat})`, `₹ ${c.amount.toLocaleString()}`, c.paymentMethod || 'UPI', c.date],
        contribColWidths,
        ['left', 'left', 'right', 'left', 'left']
      ));
      if (idx < contributions.length - 1) {
        contribRows.push(createDivider(contribColWidths, 'mid'));
      }
    });

    contribRows.push(createDivider(contribColWidths, 'bot'));
    contribRows.push('```\n');
    contribSection = contribRows.join('\n');
  }

  return (
    `🌟 *AMA COMMUNITY EVENT PLAN & SCHEDULE* 🌟\n` +
    `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n` +
    overviewTable + '\n\n' +
    scheduleSection +
    budgetSection +
    purchaserSection +
    itemizedSection +
    contribSection +
    `🗓️ *ONE-TAP CALENDAR BLOCK:* Tap link below to block your Google/Apple Calendar:\n` +
    `${gcalUrl}\n\n` +
    `💡 *Instructions for Attendees:*\n` +
    `• Please assemble 15 minutes prior to scheduled departure time.\n` +
    `• Carry society identity badge and personal essentials.\n` +
    `• For any queries, contact ${event.organizerName} at Flat ${event.organizerFlat}.`
  );
}

/**
 * Dispatches the formatted event plan via WhatsApp or Web Share.
 */
export async function shareEventPlanOnWhatsApp(
  event: SocietyEvent
): Promise<{ success: boolean; method: string }> {
  const message = formatEventWhatsAppPlan(event);
  const encodedText = encodeURIComponent(message);
  const whatsappUrl = `whatsapp://send?text=${encodedText}`;
  const webWhatsappUrl = `https://api.whatsapp.com/send?text=${encodedText}`;

  // 1. Try direct WhatsApp deep-link
  try {
    const canOpen = await Linking.canOpenURL(whatsappUrl);
    if (canOpen) {
      await Linking.openURL(whatsappUrl);
      return { success: true, method: 'whatsapp-native' };
    }
  } catch (e) {}

  // 2. Try Web Share API if supported on web browser
  if (Platform.OS === 'web' && typeof window !== 'undefined' && typeof navigator !== 'undefined') {
    if (navigator.share) {
      try {
        await navigator.share({
          title: `AMA Event Plan - ${event.title}`,
          text: message,
        });
        return { success: true, method: 'web-share' };
      } catch (err: any) {
        if (err.name === 'AbortError') {
          return { success: false, method: 'cancelled' };
        }
      }
    }

    // Open WhatsApp Web
    try {
      window.open(webWhatsappUrl, '_blank');
      return { success: true, method: 'whatsapp-web' };
    } catch (e) {}
  }

  // 3. Fallback to standard React Native Share
  try {
    await Share.share({
      title: `Event Plan - ${event.title}`,
      message,
    });
    return { success: true, method: 'react-native-share' };
  } catch (err) {
    Alert.alert('Share Failed', 'Unable to open share sheet.');
    return { success: false, method: 'error' };
  }
}

/**
 * Copies the complete formatted plan to clipboard.
 */
export async function copyEventPlanToClipboard(event: SocietyEvent): Promise<boolean> {
  const message = formatEventWhatsAppPlan(event);
  try {
    if (Platform.OS === 'web' && typeof navigator !== 'undefined' && navigator.clipboard) {
      await navigator.clipboard.writeText(message);
      Alert.alert('Copied to Clipboard!', 'Complete event plan & schedule is copied. You can paste it directly into WhatsApp!');
      return true;
    }
  } catch (e) {}

  // Native share fallback
  await Share.share({ message });
  return true;
}
